version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=root:Lucaslol123#@tcp(mysql:3306)/fornecedores?charset=utf8&parseTime=True&loc=Local
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Lucaslol123#
      - MYSQL_DATABASE=fornecedores
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
