version: '3'
services:
  app:
    image: fornecedores_notre
    build: 
      context: .
    env_file:
      - .env  # Variáveis de ambiente da aplicação
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:  # Variáveis de ambiente do MySQL
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
